name: Daily Weather Update

on:
  schedule:
    - cron: '0 23 * * *'  # 台灣時間每天 07:00 執行（UTC+8 → 23:00 UTC）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib requests

      - name: Install Noto Sans TC font manually
        run: |
          sudo apt-get update
          sudo apt-get install -y fontconfig wget
          wget -q https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKtc-hinted.zip
          unzip NotoSansCJKtc-hinted.zip -d noto
          sudo mv noto/*.otf /usr/share/fonts/
          sudo fc-cache -fv

      - name: Generate weather_diary.py from template
        run: sed "s/YOUR_API_KEY/${{ secrets.WEATHER_API_KEY }}/" weather_diary.py.template > weather_diary.py

      - name: Run weather script
        run: python weather_diary.py

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "每日氣象更新：$(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
